[[Interaction_with_other_proposals]]
== Interaction with other proposals

This section discusses how MPU interacts with other (ongoing) proposals. 

*RISC-V PMP enhancements*: MPU is compatible with ePMP proposal, and uses almost the same encoding as ePMP. 

*J-extension pointer masking proposal*: When both PM and MPU are used, MPU checking should be performed using the actual addresses generated by PM (pointer masking). 

*Hypervisor extension*: To support both MPU and hypervisor extension, there are some further changes. 

. vMPU extension: MPU used in a guest
* First, a set of vMPU CSRs for the VS-mode are required, including 16 vmpu address registers and 4 configuration registers. When V=1, vmpu CSR substitutes for the usual mpu CSR, so instructions that normally read or modify mpu CSR actually access vmpu CSR instead. This is consistent with the paging in VS-mode (i.e., vsatp). 
* Second, for HLV, HLVX, and HSV instructions, the hardware should perform vMPU checking before G-stage address translation (or hgMPU protection when hgatp in BARE mode). 
* Last, the vMPU checking is performed in the guest physical addresses, before G-stage address translation (or hgMPU protection when hgatp in BARE mode).

. hgMPU extension: MPU for protecting a hypervisor from guests (only enabled when hgatp is set to BARE mode)
* First, when hgMPU is enabled, all guest memory accesses will be checked by hgMPU; while hypervisor (in HS mode) and HU mode applications will not be affected.
* Second, a set of hgMPU CSRs for the HS-mode are required, including 16 hgmpuaddr address registers and 4 hgmpucfg configuration registers. When V=1, and hgatp.MODE=Bare,  hgmpu is used to provide isolation between hypervisor and guest VMs.
* Third, an XLEN-bit read/write CSR hgmpuswitch is also provided in hgMPU, which is identical to mpuswitch shown in Figure 7. During context switch, the hypervisor can simply store and restore hgmpuswitch as part of the context. A region is activated only when both corresponding bits in hgmpuswitch and A field of hgmpuicfg are set. (i.e., hgmpuswitch[i] & hgmpuicfg.A)
* Last, the hgMPU checking is performed after the guest address translation (or vMPU checking), before PMP checking.

As hgMPU does not apply on hypervisor, the encodings of configuration registers are simplified as the following table.

The encodings of hgmpucfg are shown in the table:

[cols="^1,^1,^1,^1,^4",stripes=even,options="header"]
|===
4+|Bits on _hgmpucfg_ register |Result
|S|R|W|X|V Mode (VS + VU)
|0|0|0|0|Inaccessible region (Access Exception)
|0|0|0|1|Execute-only region
|0|1|0|0|Read-only region
|0|1|0|1|Read/Execute region
|0|1|1|0|Read/Write region
|0|1|1|1|Read/Write/Execute region
4+|Others|Reserved
|===