[[Interaction_with_hypervisor_extension]]
== Interaction with hypervisor extension

To support both MPU and hypervisor extension, there are some further changes. 

=== vMPU extension

This extension describes how MPU is used in a guest VM.

1. A set of vMPU CSRs for the VS-mode are required, including 64 vMPU address registers and 16 configuration registers.
When V=1, vMPU CSR substitutes for the usual MPU CSR, so instructions that normally read or modify MPU CSR actually access vMPU CSR instead.
This is consistent with the paging in VS-mode (i.e., vsatp). 
2. For HLV, HLVX, and HSV instructions, the hardware should perform vMPU checking before G-stage address translation (or hgMPU protection when hgatp in BARE mode). 
3. The vMPU checking is performed in the guest physical addresses, before G-stage address translation (or hgMPU protection when hgatp in BARE mode).


=== hgMPU extension

This extension describes how MPU is used for protecting a hypervisor from guests (only enabled when hgatp is set to BARE mode).

1. When hgMPU is enabled, all guest memory accesses will be checked by hgMPU; while hypervisor (in HS mode) and HU mode applications will not be affected.
2. A set of hgMPU CSRs for the HS-mode are required, including 64 hgMPUaddr address registers and 16 hgMPUcfg configuration registers.
When V=1, and hgatp.MODE=Bare, hgMPU is used to provide isolation between hypervisor and guest VMs.
3. XLEN-bit read/write hgmpuswitch0 and hgmpuswitch1 CSRs are also provided in hgMPU, which are identical to mpuswitch0 and mpuswitch1 shown in Figure 7.
Only hgmpuswitch0 is used for RV64.
During context switch, the hypervisor can simply store and restore hgmpuswitch (we use hgmpuswitch to represent either hgmpuswitch0 or hgmpuswitch1) as part of the context.
A region is activated only when both corresponding bits in hgmpuswitch and A field of hgmpuicfg are set. (i.e., hgmpuswitch[i] & hgmpuicfg.A)
4. The hgMPU checking is performed after the guest address translation (or vMPU checking), before PMP checking.

As hgMPU does not apply on hypervisor, the encodings of configuration registers are simplified as the following table.

The encodings of hgmpucfg are shown in the table:

[cols="^1,^1,^1,^1,^4",stripes=even,options="header"]
|===
4+|Bits on _hgmpucfg_ register |Result
|S|R|W|X|V Mode (VS + VU)
|0|0|0|0|Inaccessible region (Access Exception)
|0|0|0|1|Execute-only region
|0|1|0|0|Read-only region
|0|1|0|1|Read/Execute region
|0|1|1|0|Read/Write region
|0|1|1|1|Read/Write/Execute region
4+|Others|Reserved
|===
